globals:
  ex_name: test5
  debug: true
  num_epochs: 100
  seed: 42
  user: miyazaki
data:
  test_data_dir: ./input/petfinder-pawpularity-score/test
  test_df_path: ./input/petfinder-pawpularity-score/test.csv
  train_data_dir: ./input/petfinder-pawpularity-score/train
  train_df_path: ./input/petfinder-pawpularity-score/train.csv
defaults:
- model: EffV2_plus_table
- dataset: Image_plus_table
- loader: DefaultDataloader
- split: StratifiedKFold
- optimizer: Adam
- loss: BCEwithLogitsLoss
- scheduler: CosineAnnealingLR
- callback: DefaultCallback
hydra:
  run:
    dir: ./outputs/${globals.ex_name}
  sweep:
    dir: ./outputs/${globals.ex_name}
    subdir: ${model.name} - ${dataset.name}
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s] line%(lineno)d [%(levelname)s] %(message)s'
