
globals:
  comment: null # コマンドラインから入力する
  debug: true
  device: cuda
  ex_name: 000_base_line_search
  num_epochs: 100
  seed: 42
  use_amp: false

# データのディレクトリ
data:
  test_data_dir: ./input/petfinder-pawpularity-score/test
  test_df_path: ./input/petfinder-pawpularity-score/test.csv
  train_data_dir: ./input/petfinder-pawpularity-score/train
  train_df_path: ./input/petfinder-pawpularity-score/train.csv

# モデル学習の設定
defaults:
  - model: EffNetV2_b0
  - dataset: DefaultDataset
  - loader: DefaultDataloader
  - split: StratifiedKFold
  - optimizer: Adam
  - loss: BCEwithLogitsLoss
  - scheduler: CosineAnnealingLR
  - callback: DefaultCallback

# hydraの設定
hydra:
  run:
    dir: ./outputs/${globals.ex_name}/${now:%y%m%d}-${globals.comment}
  sweep:
    dir: ./outputs/${globals.ex_name}/${now:%y%m%d}-${globals.comment}/try0
    subdir: try${hydra.job.num}
  job_logging:
    formatters:
      simple:
        # ex: [2021-11-17 15:48:23,327][__main__] line33 [INFO] ::: success :::
        format: '[%(asctime)s][%(name)s] line%(lineno)d [%(levelname)s] %(message)s'
