globals:
  ex_name: 211116_model_test
  debug: false
  num_epochs: 100
  seed: 42
  user: miyazaki
model:
  name: NN_linear
data:
  train_data_dir: inputs/000_datasets
  train_df_path: inputs/000_datasets/train.csv
  test_data_dir: inputs/000_datasets
  test_df_path: inputs/000_datasets/test.csv
dataset:
  name: OriginDataset
  params:
    image_column: pipe
    original_temp_range:
      min: 30
      max: 65
loader:
  train:
    batch_size: 8
    num_workers: 0
    shuffle: true
  valid:
    batch_size: 8
    num_workers: 0
    shuffle: false
  test:
    batch_size: 1
    num_workers: 0
    shuffle: false
loss:
  name: RMSELoss
  params: null
optimizer:
  name: Adam
  params:
    lr: 0.0001
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10
early_stopping:
  delta: 0
  patience: 10
hydra:
  run:
    dir: ./outputs/${globals.ex_name}
  sweep:
    dir: ./outputs/${globals.ex_name}
    subdir: ${dataset.name}-${model.name}
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s] line%(lineno)d [%(levelname)s] %(message)s'
